name: Update Repo Settings

on:
  push:
    branches:
      - main

jobs:

#  setup-cli:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up GitHub CLI
#        uses: actions/setup-gh@v1
#        with:
#          gh-version: 'X.Y.Z' # Version von GitHub CLI angeben

  update-settings:
#    needs: setup-cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Repository Settings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./project/update_repo_settings.py
